[package]
name = "persian"
version = "0.1.1"
authors = ["Sajjad Hashemian <wolaws@gmail.com>"]
description = "helpers for Persian language."
license = "MIT"
repository = "https://github.com/sijad/persian-rs"
readme = "README.md"
keywords = [
  "farsi",
  "persian",
]

[dependencies]
